// Code generated by mockery v2.32.0. DO NOT EDIT.

package repomocks

import (
	models "mid-the-ethereum-fetcher-zxowaz/models"

	mock "github.com/stretchr/testify/mock"
)

// TransactionRepo is an autogenerated mock type for the TransactionRepo type
type TransactionRepo struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *TransactionRepo) GetAll() (models.Transactions, error) {
	ret := _m.Called()

	var r0 models.Transactions
	var r1 error
	if rf, ok := ret.Get(0).(func() (models.Transactions, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() models.Transactions); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(models.Transactions)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByRlphex provides a mock function with given fields: rlphex
func (_m *TransactionRepo) GetByRlphex(rlphex string) (interface{}, error) {
	ret := _m.Called(rlphex)

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interface{}, error)); ok {
		return rf(rlphex)
	}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(rlphex)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(rlphex)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionRepo creates a new instance of TransactionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepo {
	mock := &TransactionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
